# Generated by Django 4.2.7 on 2023-11-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matematicalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matematic',
            name='answer',
            field=models.TextField(),
        ),
    ]
